### ISSUE TITLE
new operator proposal: \ (inverted division)

### ISSUE THREAD

**Issue by Wintus** [shapoco/calctus#52]
# proposal

I'd like to propose a new arithmetic operation `\` (inverse division), i.e. `b\a = a/b`

cf. It's [supported in Julia][jl].
> x \ y | inverse divide | equivalent to y / x

ref. https://en.wikipedia.org/wiki/Division_(mathematics)#Notation

[jl]: https://docs.julialang.org/en/v1/manual/mathematical-operations/#Arithmetic-Operators

# motivation

It would be easy to write an expression like `ans\3` instead of `3/ans`. This will reduce the number of key types.

# technical concern

If an escape character is needed in the future, we may consider `` ` `` (backtick) instead to avoid conflict.

cf. [Powershell use backtick for escaping][pwsh].

[pwsh]: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_special_characters?view=powershell-7.2#long-description

**Comment by shapoco** [comment]
Thanks for the suggestion. I considered it, but decided not to assign functions to "\" because it is easily confused with "/".

Instead, I would like to consider: while the evaluated value is displayed, if the cursor is moved to the beginning of the line by pressing the Home key, replace the evaluated value with "ans".

**Comment by Wintus** [comment]
This choice sounds reasonable to me. Thank you for your consideration!

For now, let me leave this issue open, and please feel free to close it when you open an issue for the alternative.
